version: '3'

services:

  api:
    image: phpswoole/swoole:latest
    container_name: swoole
    ports:
      - 9501:9501
    volumes:
      - ./site/:/var/www
    links:
      - mysql
    command:
      - ./server.php
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql57
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: veiculos
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username

  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./site/html:/usr/share/nginx/html/
    ports:
      - "9090:80"
    environment:
      - NGINX_HOST=4events-processo-seletivo.com
      - NGINX_PORT=80

  live-reloader:
    image: apogiatzis/livereloading
    container_name: livereloader
    privileged: true
    environment:
      - RELOAD_DELAY=1.5              # seconds
      - RELOAD_CONTAINER=swoole
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./site:/var/www/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80